server:
  port: 8088

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/mall?serverTimezone=GMT%2B8
    username: root
    password: password

#mybatis-plus配置控制台打印完整带参数SQL语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapping/*.xml

# 自定义的属性
custom:
  cart:
    max_capacity: 5
  email:
    resend-api: re_3T5LVhhh_6riXhZFfaxBnw3A8q4gmDtju
    from: cngo<no-reply@cngo.cloudns.nz>

