server:
  port: ${LEANCLOUD_APP_PORT:8088}

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: ${DB_URL:jdbc:mysql://localhost:3306/miaosha?useSSL=false&serverTimezone=UTC}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}

#mybatis-plus配置控制台打印完整带参数SQL语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapping/*.xml

# 自定义的属性
custom:
  cart:
    max_capacity: 5
  email:
    resend-api: ${RESEND_API}
    from: ${FROM_EMAIL:cngo<no-reply@cngo.cloudns.nz>}

